dmitry-honcharuk/arthouse

app/modules/common/layout.tsx, app/modules/projects/create-project.ts, app/modules/projects/get-project-path.ts, app/modules/projects/get-user-project.ts, app/modules/users/components/profile/profile-details.section.tsx, app/modules/users/components/profile/social-links-edit.tsx, app/modules/users/getURI.tsx, app/modules/users/getUserById.ts, app/modules/validation/validate-form-data.ts, app/routes/$id/index.tsx, app/routes/$user.tsx, app/routes/$user/$project.tsx, app/routes/$user/index.tsx, app/routes/$user/profile.tsx, app/routes/projects.tsx, app/routes/projects/new.tsx, app/server/get-logged-in-user.server.ts, package-lock.json, package.json, prisma/migrations/20220417205630_projects/migration.sql, prisma/migrations/20220417212820_user_projects/migration.sql, prisma/migrations/20220417213444_add_project_caption/migration.sql, prisma/migrations/20220417232152_remove_unique_user_id_index_from_projects/migration.sql, prisma/migrations/20220418151741_add_project_slug/migration.sql, prisma/migrations/20220418180934_project_status/migration.sql, prisma/migrations/20220418181112_update_status_enum/migration.sql, prisma/migrations/20220418200543_uniq_slug_per_account/migration.sql, prisma/schema.prisma
adds project creation page
adds project details page skeleton
Resolves #16
=> adds project entity

app/modules/users/components/profile/social-links-display.tsx
=> amends social link if link is an email

app/modules/projects/update-project.ts, app/routes/$user/$project/index.tsx
=> implements project publish unpublish

app/modules/projects/components/project-preview-form.tsx, app/modules/projects/create-project-item.ts, app/modules/projects/update-project.ts, app/routes/$user/$project/index.tsx, app/routes/$user/index.tsx, prisma/migrations/20220424172534_project_preview/migration.sql, prisma/schema.prisma
=> implements project preview

app/modules/projects/components/img-form.tsx, app/routes/$user/$project/$item.ts, app/routes/index.tsx, app/server/action-builder.server.ts, package-lock.json, package.json, tsconfig.json
fixed img slide was not updating
Resolves #42
=> upgraded remix packages

app/modules/common/breadcrumbs.tsx, app/modules/common/layout.tsx, app/modules/common/page-layout.tsx, app/modules/common/user-personal-navigation.tsx, app/modules/projects/components/project-screen.tsx, app/modules/users/components/user-layout.tsx, app/routes/$user/$project/index.tsx, app/routes/$user/$project/settings.tsx, app/routes/$user/albums/$album/$project.tsx, app/routes/$user/albums/$album/index.tsx, app/routes/$user/favorites.tsx, app/routes/$user/index.tsx, app/routes/$user/profile.tsx, app/routes/albums/new.tsx, app/routes/projects/new.tsx
amended ui to have breadcrumbs on all pages except root
=> implemented breadcrumbs component

app/modules/projects/components/project-preview-form.tsx, app/modules/users/components/user-layout.tsx
=> added fields param to preview removal submit

app/modules/projects/components/project-screen.tsx, app/modules/projects/components/project-settings/general-settings.tsx, app/modules/projects/update-project.ts, app/routes/$user/$project/settings.tsx
=> adds project settings section to edit project title, slug and caption

app/modules/projects/components/project-item.tsx, app/modules/projects/delete-project.ts, app/modules/users/components/profile/section-title.tsx, app/routes/$user/$project/settings.tsx, app/routes/$user/albums/$album/settings.tsx
=> adds danger section to the project settings page with a delete cta

app/modules/projects/components/project-settings/general-settings.tsx, app/routes/$user/$project/settings.tsx
added message to show if no description
amended delete project modal content
=> fixed description icon color

.github/workflows/deploy.yaml, app/modules/albums/delete-album.ts, app/modules/albums/get-album-secret-key.ts, app/modules/albums/set-album-password.server.ts, app/modules/common/security-switch-setting.tsx, app/modules/crypto/get-decrypted-security.ts, app/modules/projects/delete-project.ts, app/modules/projects/get-project-secret-key.ts, app/modules/projects/set-project-password.server.ts, app/routes/$user/$project/authorize.tsx, app/routes/$user/$project/settings.tsx, app/routes/$user/albums/$album/authorize.tsx, app/routes/$user/albums/$album/settings.tsx, app/server/action-builder.server.ts, prisma/migrations/20220517235640_project_deletion_cascades/migration.sql, prisma/migrations/20220518000232_album_deletion_cascade/migration.sql, prisma/migrations/20220518000917_project_favourites_deletion_cascade/migration.sql, prisma/schema.prisma
implemented on-delete cascades for projects and albums tables
Resolves #62
=> implemented album deletion section

.github/workflows/deploy.yaml, app/modules/projects/components/project-screen.tsx, app/modules/projects/components/project-tags-form.tsx, app/modules/projects/components/tags-card.tsx, app/modules/projects/get-user-project.ts, app/modules/projects/set-tags.ts, app/modules/tags/types/with-tags.ts, app/routes/$user/$project/index.tsx, app/routes/$user/$project/settings.tsx, app/routes/$user/albums/$album/$project.tsx, prisma/migrations/20220518213621_tags/migration.sql, prisma/migrations/20220518215121_m_n_tags/migration.sql, prisma/schema.prisma
=> Implemented tag entity

.github/workflows/deploy.yaml, app/db.server.ts, app/modules/favorites/add-favorite.ts, app/modules/favorites/delete-favorite.ts, app/modules/projects/dashboard/dashboard-sorting.ts, app/modules/projects/dashboard/get-latest-projects.ts, app/modules/projects/dashboard/get-projects-for-dashboard.ts, app/modules/projects/dashboard/get-trending-projects.ts, app/modules/projects/dashboard/index.ts, app/modules/projects/dashboard/is-dashboard-sorting.tsx, app/modules/projects/get-projects.ts, app/routes/index.tsx, prisma/migrations/20220523202732_favourite_created_date/migration.sql, prisma/migrations/20220523215523_favorite_count/migration.sql, prisma/schema.prisma
=> implemented dashboard sorting

app/modules/categories/components/categories-autocomplete-field.tsx, app/modules/categories/components/categories-autocomplete.tsx, app/modules/projects/components/project-categories-form.tsx, app/modules/projects/dashboard/get-latest-projects.ts, app/modules/projects/dashboard/get-projects-for-dashboard.ts, app/modules/projects/dashboard/get-trending-projects.ts, app/modules/projects/get-projects.ts, app/modules/search/components/search-form.tsx, app/routes/index.tsx
fixed bug on search with categories disappear from query
added delete button on category chips on project page
=> implemented categories filter on dashboard

app/db.server.ts, app/modules/projects/components/project-tags-form.tsx, app/modules/projects/dashboard/get-latest-projects.ts, app/modules/projects/dashboard/get-trending-projects.ts, app/modules/projects/get-projects.ts, app/routes/search.tsx
allows tags to be created in any case
Resolves #77
=> amends tags search to be case insensitive

app/modules/common/user-personal-navigation.tsx, app/modules/projects/components/project-screen.tsx, app/modules/users/add-follower.ts, app/modules/users/components/follow-button.tsx, app/modules/users/get-followed-users.ts, app/modules/users/is-following.ts, app/modules/users/remove-follower.ts, app/routes/$user/$project/index.tsx, app/routes/$user/following.tsx, app/routes/$user/index.tsx, app/routes/follows/$userId.ts, prisma/migrations/20220602202607_followers/migration.sql, prisma/schema.prisma
adds follow/unfollow button to user personal page
Resolves #79
=> introduces follow connections between users

app/routes/healthz.ts, deploy/deployment.yaml
Adds deployment readiness probe
Resolves #70
=> fixes deployment downtime

.github/workflows/deploy.yaml, app/modules/email/email.service.ts, app/modules/email/index.ts, app/modules/email/providers/sendinblue/sendinblue-email.service.ts, app/modules/email/types/email-service.ts, app/modules/email/types/email-type.ts, app/modules/email/types/index.ts, app/modules/email/types/send-options.ts, package-lock.json, package.json
=> introduced sendinblue email provider

app/routes/$user/albums/$album/index.tsx
=> fixes bug with "add projects" button displayed for non-creator user

app/modules/auth/social-strategy/facebook.social-strategy.ts, app/modules/auth/social-strategy/google.social-strategy.ts, app/modules/auth/types/social-user.ts, app/modules/common/header.tsx, app/modules/common/href-link.tsx, app/modules/projects/components/project-card.tsx, app/modules/projects/components/project-screen.tsx, app/modules/users/components/profile/profile-details.section.tsx, app/modules/users/get-user-by-social.ts, app/modules/users/utils/get-full-name.ts, app/routes/$user/following.tsx, app/routes/$user/index.tsx, app/routes/$user/profile.tsx, app/routes/authenticate.tsx, package.json, prisma/migrations/20220608121403_add_new_profile_fields/migration.sql, prisma/schema.prisma
=> add fn and ln editing in profile

app/server/upload-handler.server.ts
removes original filename from bucket object name
Resolves #99
=> amends filename generation to be cloudflare proxy instead of AWS S3 name

app/modules/auth/jwt/admin-token.server.ts, app/modules/auth/types/with-permissions.ts, app/modules/auth/types/with-roles.ts, app/modules/users/admins/get-admin-by-email.ts, app/routes/admin/current.ts, app/routes/admin/index.ts, app/routes/admin/login.ts, app/routes/admin/logout.ts, app/routes/admin/projects/$id.ts, app/routes/admin/projects/index.ts, app/routes/admin/users/$id.ts, app/routes/admin/users/index.ts, app/server/action-builder.server.ts, prisma/migrations/20220625000413_permissions/migration.sql, prisma/migrations/20220625000515_superadmin_role/migration.sql, prisma/migrations/20220626202833_permissions/migration.sql, prisma/schema.prisma
amends admin login token payload
=> adds roles and permissions
